package core;

public enum Block {
	BLOCK_GRASS,
	ROAD_VERTICAL,
	ROAD_HORIZZONTAL,
	ROAD_RIGHT_DOWN,
	ROAD_LEFT_DOWN,
	ROAD_RIGHT_UP,
	ROAD_LEFT_UP,
	ROAD_HORIZZONTAL_START,
	ROAD_VERTICAL_START;
}
